name: chosen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  table_calendar: ^3.0.9
  intl: ^0.18.1
  timezone: ^0.9.2
  provider: ^6.1.1
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true